version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    restart: always

  api:
    image: node
    tty: true
    stdin_open: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - db
    restart: always
